### ISSUE TITLE
Wrong Arma2OA Beta Patch version

### ISSUE THREAD

**Issue by Svenskunganka** [denisio/Dayz-Epoch-Linux-Server#22]
The server is reporting the wrong Arma2OA beta patch version. I have 103718 installed, but it reports 102451 to DayZ commander.

Any clues why this is happening?

**Comment by BangL** [comment]
because it IS 102451.
https://community.bistudio.com/wiki/ArmA:_Dedicated_Server#Linux_3

**Comment by Svenskunganka** [comment]
Alright, any idea when the 103718 version is going to be released? Right now I can't get any players on the server since everyone has ticked 'Hide Wrong Arma Version' in DayZCommander.

**Comment by BangL** [comment]
for linux? never. 103718 is a windows build.
on the other hand there will never be any 102451 build for windows, since its a linux build.
but that doesnt mean that its incompatible to each other. the more interesting part is the 1.62.x

The fact that it counts as a "Wrong Arma Version" is a problem of the devs of DayZCommander, not of denisio or bohemia. maybe you should report it here: https://dayzcommander.zendesk.com/hc/en-us , if you really care about it.

**Comment by denisio** [comment]
http://forums.bistudio.com/showthread.php?168768-ARMA-2-Operation-Arrowhead-Linux-Server-beta-1-63-112555

**Comment by Jarrrk** [comment]
So this server implementation is useless until you integrate it with the new 1.63 changes, is this going to happen? Or should I start my own project?
